### ISSUE TITLE
Error running on Server2008R2 Node

### ISSUE THREAD

**Issue by MartinGeierino** [DexterPOSH/PSRemotely#54]
Hi,
running a simple test on a Server 2008R2 node produces following error:

VERBOSE: Helper.ps1 - Start-RemotelyJobProcessing - LineNo : 169 - PSRemotely job finished for Node ->
test03.xxx.de. Processing it now.
VERBOSE: Helper.ps1 - ProcessRemotelyOutputToJSON - LineNo : 170 - Cannot validate argument on parameter
'testResult'. The argument is null or empty. Provide an argument that is not null or empty, and then try the
command again.
VERBOSE: Invoke-PSRemotely.ps1 - Invoke-PSRemotely<Process> - LineNo : 202 - Error occurred in test script
'C:\PSRemotely Tests\Tests\Test.PSRemotely.ps1 -> at ProcessRemotelyOutputToJSON, C:\Program
Files\WindowsPowerShell\Modules\PSRemotely\1.0.3\Private\Helper.ps1: line 68

Running the same test against a Server 2012R2 node results in no errors.
Both have WMF updated to version 5.1.

**Comment by DexterPOSH** [comment]
Thanks, @MartinGeierino for opening this issue.
I will take a look into this. This has never been tested on a Server 2K8R2 box before but IMO it should be fine if it has WMF5.1

**Comment by DexterPOSH** [comment]
This might sound funny, but I do not have even a single test VM running Server2008R2. I will take some time this week to spin up a new VM for testing.

**Comment by DexterPOSH** [comment]
@MartinGeierino I just ran a simple test on Server2008R2 node and it worked. 
I am suspecting the issue here is related to the issue #55 which is fixed in the Dev branch for now.
I will be running entire integration test suite on 2K8 R2 box to be sure about this though.

**Comment by DexterPOSH** [comment]
Ran this against a Server 2008R2 node running WMF 5.1 and it worked (on the dev branch).
Working on pushing the release of the new version.

![psremotely_targets_2k8r2box](https://cloud.githubusercontent.com/assets/6275375/26390894/2021d7ee-407e-11e7-9d1e-ce94be8335e0.gif)

**Comment by DexterPOSH** [comment]
Hi @MartinGeierino 
The v1.0.4 is released to PSGallery now.
https://www.powershellgallery.com/packages/PSRemotely/1.0.4

If you get time then please do test it on your 2008R2 node and re-open the issue, if it still persists.
